//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirExportBkg
    {
        public int SequenceId { get; set; }
        public string SchNo { get; set; }
        public string BkgRefNo { get; set; }
        public string ExportNo { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string FinDest { get; set; }
        public string ShipperId { get; set; }
        public string ShipperContact { get; set; }
        public string ShipperTel { get; set; }
        public string ShipperFax { get; set; }
        public string ShipperEmail { get; set; }
        public string TsInd { get; set; }
        public string TsJobNo { get; set; }
        public string AsAgent { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string Remark { get; set; }
        public string Marking { get; set; }
        public string CollectFrom { get; set; }
        public string CargoType { get; set; }
        public string CargoClass { get; set; }
        public string CargoLevel { get; set; }
        public string CargoRef { get; set; }
        public string CargoFp { get; set; }
        public string CargoImo { get; set; }
        public string CargoLength { get; set; }
        public string CancelInd { get; set; }
        public string CancelRmk { get; set; }
        public string CancelUser { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    }
}
