//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_Location
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string user { get; set; }
        public string geo_device { get; set; }
        public string geo_latitude { get; set; }
        public string geo_longitude { get; set; }
        public string note1 { get; set; }
        public string note2 { get; set; }
        public string note3 { get; set; }
        public string note4 { get; set; }
        public Nullable<System.DateTime> create_date_time { get; set; }
    }
}
