//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_Job_Stock
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string StockStatus { get; set; }
        public string StockDescription { get; set; }
        public string StockMarking { get; set; }
        public Nullable<decimal> StockQty { get; set; }
        public string StockUnit { get; set; }
        public Nullable<decimal> PackingQty { get; set; }
        public string PackingUnit { get; set; }
        public string PackingDimention { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
    }
}
