//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimension
    {
        public int Id { get; set; }
        public Nullable<int> HouseId { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string Uom { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string WeightUnit { get; set; }
        public Nullable<decimal> Width { get; set; }
        public string WidthUnit { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string HeightUnit { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string LengthUnit { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string VolumeUnit { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> RowCreateTime { get; set; }
        public string RowCreateUser { get; set; }
        public Nullable<System.DateTime> RowUpdateTime { get; set; }
        public string RowUpdateUser { get; set; }
        public Nullable<decimal> TotalWt { get; set; }
        public Nullable<decimal> TotalVol { get; set; }
        public Nullable<decimal> SkuQty { get; set; }
        public Nullable<decimal> PackQty { get; set; }
        public Nullable<decimal> WholeQty { get; set; }
        public Nullable<decimal> LooseQty { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SingleWeight { get; set; }
        public string PipeNo { get; set; }
        public string HeatNo { get; set; }
        public string TypeCode { get; set; }
    }
}
