//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_PayrollDet
    {
        public int Id { get; set; }
        public Nullable<int> PayrollId { get; set; }
        public string ChgCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string Pic { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string SignNo { get; set; }
        public Nullable<decimal> Before { get; set; }
    }
}
