//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_PayItem
    {
        public string Code { get; set; }
        public string Description { get; set; }
        public string IsDefault { get; set; }
        public string ProcessNote { get; set; }
        public string ProcessType { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> CpfRate { get; set; }
        public string IrasType { get; set; }
        public string Group1 { get; set; }
        public string Group2 { get; set; }
        public string Group3 { get; set; }
        public string Group4 { get; set; }
        public string Group5 { get; set; }
        public string Group6 { get; set; }
        public string IsCpf { get; set; }
    }
}
