//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_quote
    {
        public int Id { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string DocType { get; set; }
        public string JobType { get; set; }
        public string JobNo { get; set; }
        public string RefNo { get; set; }
        public string PartyId { get; set; }
        public string PartyContact { get; set; }
        public string PartyEmail { get; set; }
        public string PartyMobile { get; set; }
        public string PartyAddress { get; set; }
        public string PartyRemark { get; set; }
        public string SalesId { get; set; }
        public string SalesRemark { get; set; }
        public string DocNote { get; set; }
        public string DocStatus { get; set; }
        public string WorkStatus { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public string DocRemark { get; set; }
        public Nullable<System.DateTime> DateEffective { get; set; }
        public Nullable<System.DateTime> DateExpiry { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string RowStatus { get; set; }
        public string RowCreateUser { get; set; }
        public Nullable<System.DateTime> RowCreateTime { get; set; }
        public string RowUpdateUser { get; set; }
        public Nullable<System.DateTime> RowUpdateTime { get; set; }
    }
}
