//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_house
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string JobNo { get; set; }
        public string ContNo { get; set; }
        public Nullable<int> LineId { get; set; }
        public string JobType { get; set; }
        public string TransJobOrder { get; set; }
        public string TransImpId { get; set; }
        public string BookingNo { get; set; }
        public string HblNo { get; set; }
        public string DoNo { get; set; }
        public string SkuCode { get; set; }
        public string UomCode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string CargoType { get; set; }
        public string Marking1 { get; set; }
        public string Marking2 { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public string TallyBox { get; set; }
        public Nullable<bool> IsDg { get; set; }
        public Nullable<bool> IsOverLength { get; set; }
        public string DgClass { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string CargoStatus { get; set; }
        public Nullable<bool> IsHold { get; set; }
        public Nullable<bool> IsBill { get; set; }
        public Nullable<bool> IsNormal { get; set; }
        public Nullable<decimal> QtyOrig { get; set; }
        public string PackTypeOrig { get; set; }
        public Nullable<decimal> WeightOrig { get; set; }
        public Nullable<decimal> VolumeOrig { get; set; }
        public Nullable<bool> IsLong { get; set; }
        public Nullable<System.DateTime> RecDate { get; set; }
        public string RecUser { get; set; }
        public string RecNote { get; set; }
        public string CheckInDate { get; set; }
        public string Commodity { get; set; }
        public string CommodityRmk { get; set; }
        public string LandStatus { get; set; }
        public Nullable<decimal> BalanceQty1 { get; set; }
        public string Pod { get; set; }
        public string ClientId { get; set; }
        public string ClientContact { get; set; }
        public string ClientEmail { get; set; }
        public string ShipperInfo { get; set; }
        public string ShipperRemark { get; set; }
        public string ShipperEmail { get; set; }
        public string ConsigneeInfo { get; set; }
        public string ConsigneeRemark { get; set; }
        public string ConsigneeEmail { get; set; }
        public string NotifyInfo { get; set; }
        public string NotifyRemark { get; set; }
        public string NotifyEmail { get; set; }
        public string TransportNeed { get; set; }
        public string TransportCode { get; set; }
        public string TransportRemark { get; set; }
        public string TransportEmail { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string Pol { get; set; }
        public Nullable<System.DateTime> Eta { get; set; }
        public Nullable<System.DateTime> Etd { get; set; }
        public string CarrierCode { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Prepaid_Ind { get; set; }
        public Nullable<decimal> Collect_Amount1 { get; set; }
        public Nullable<decimal> Collect_Amount2 { get; set; }
        public string Duty_Payment { get; set; }
        public string Incoterm { get; set; }
        public string EtaTime { get; set; }
        public string EtdTime { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Responsible { get; set; }
        public string OpsType { get; set; }
        public Nullable<decimal> PackQty { get; set; }
        public string PackUom { get; set; }
        public Nullable<decimal> WholeQty { get; set; }
        public string WholeUom { get; set; }
        public string BalanceUom { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> LengthPack { get; set; }
        public Nullable<decimal> WidthPack { get; set; }
        public Nullable<decimal> HeightPack { get; set; }
        public string DamagedStatus { get; set; }
        public string TransferNo { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public string UserId { get; set; }
        public Nullable<decimal> GstFee { get; set; }
        public Nullable<decimal> PermitFee { get; set; }
        public Nullable<decimal> HandlingFee { get; set; }
        public Nullable<decimal> OtherFee { get; set; }
        public string Currency { get; set; }
        public string BkgSKuCode { get; set; }
        public Nullable<decimal> BkgSkuQty { get; set; }
        public string BkgSkuUnit { get; set; }
        public Nullable<decimal> Ocean_Freight { get; set; }
        public string SealNo { get; set; }
        public string PermitBy { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ClientAddress { get; set; }
        public string ShipperAddress { get; set; }
        public string NotifyAddress { get; set; }
        public Nullable<int> ContId { get; set; }
        public string BookingItem { get; set; }
        public string ActualItem { get; set; }
        public string TripIndex { get; set; }
        public Nullable<int> TripId { get; set; }
        public string PermitNo { get; set; }
        public string StorageType { get; set; }
        public Nullable<System.DateTime> StockDate { get; set; }
        public Nullable<System.DateTime> NextBillDate { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public string PoNo { get; set; }
        public Nullable<System.DateTime> BillingStartDate { get; set; }
        public string InventoryId { get; set; }
        public string PalletNo { get; set; }
        public string CartonNo { get; set; }
        public string Mft_LotNo { get; set; }
        public Nullable<System.DateTime> Mft_LotDate { get; set; }
        public Nullable<System.DateTime> Mft_ExpiryDate { get; set; }
        public string OnHold { get; set; }
    }
}
