//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuBasicMast
    {
        public int SequenceId { get; set; }
        public string MasterId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Color { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public int SortIndex { get; set; }
        public string RoleName { get; set; }
        public string Img { get; set; }
    }
}
