//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackingLotItem
    {
        public int Id { get; set; }
        public string PLCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string JobType { get; set; }
        public Nullable<int> TripId { get; set; }
        public string ContinerNo { get; set; }
        public string DriverCode { get; set; }
        public string Trailer { get; set; }
        public string StatusCode { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Note5 { get; set; }
    }
}
