//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class pts_record
    {
        public int Id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string company_reg { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> cate_id { get; set; }
        public Nullable<int> item_id { get; set; }
        public Nullable<int> case_id { get; set; }
        public Nullable<int> pts_index { get; set; }
        public Nullable<decimal> pts_value { get; set; }
        public Nullable<System.DateTime> review_time { get; set; }
        public string review_user { get; set; }
        public string pts_user { get; set; }
    }
}
