//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class pts_case
    {
        public int Id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string company_reg { get; set; }
        public Nullable<int> pts_type_id { get; set; }
        public string case_code { get; set; }
        public string case_name { get; set; }
        public string client_code { get; set; }
        public string admin_user { get; set; }
    }
}
