//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_VehicleFuel
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string DriverCode { get; set; }
        public string VehicleCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> OpenLiter { get; set; }
        public Nullable<decimal> CloseLiter { get; set; }
        public Nullable<decimal> NewLiter { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public string DocNo { get; set; }
        public string SupplierCode { get; set; }
        public string Remark { get; set; }
    }
}
