//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_LC
    {
        public int Id { get; set; }
        public string LcNo { get; set; }
        public string LcTempNo { get; set; }
        public string LcType { get; set; }
        public string LcRef { get; set; }
        public Nullable<System.DateTime> LcAppDate { get; set; }
        public Nullable<System.DateTime> LcExpirtDate { get; set; }
        public string LcExpirtPlace { get; set; }
        public string LcEntityCode { get; set; }
        public string LcEntityName { get; set; }
        public string LcEntityAddress { get; set; }
        public string LcBeneCode { get; set; }
        public string LcBeneName { get; set; }
        public string LcBeneAddress { get; set; }
        public string BankCode { get; set; }
        public string BankName { get; set; }
        public string BankBranch { get; set; }
        public string BankAddress { get; set; }
        public string BankRef { get; set; }
        public Nullable<int> BankTenor { get; set; }
        public Nullable<decimal> LcAmount { get; set; }
        public string LcCurrency { get; set; }
        public Nullable<decimal> LcExRate { get; set; }
        public string LcMode { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
    }
}
