//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_product
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string PartyId { get; set; }
        public string ProductClass { get; set; }
        public string ProductType { get; set; }
        public string BrandName { get; set; }
        public string StatusCode { get; set; }
        public string Description { get; set; }
        public string UomPacking { get; set; }
        public string UomWhole { get; set; }
        public string UomLoose { get; set; }
        public Nullable<int> QtyPackingWhole { get; set; }
        public Nullable<int> QtyWholeLoose { get; set; }
        public Nullable<decimal> LengthPacking { get; set; }
        public Nullable<decimal> WidthPacking { get; set; }
        public Nullable<decimal> HeightPacking { get; set; }
        public Nullable<decimal> VolumePacking { get; set; }
        public Nullable<decimal> LengthWhole { get; set; }
        public Nullable<decimal> WidthWhole { get; set; }
        public Nullable<decimal> HeightWhole { get; set; }
        public Nullable<decimal> VolumeWhole { get; set; }
        public Nullable<decimal> LengthLoose { get; set; }
        public Nullable<decimal> WidthLoose { get; set; }
        public Nullable<decimal> HeightLoose { get; set; }
        public Nullable<decimal> VolumeLoose { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> Saleprice { get; set; }
        public string Country { get; set; }
        public string Att1 { get; set; }
        public string Att2 { get; set; }
        public string Att3 { get; set; }
        public string Att4 { get; set; }
        public string Att5 { get; set; }
        public string Att6 { get; set; }
        public string Att7 { get; set; }
        public string Att8 { get; set; }
        public string Att9 { get; set; }
        public string Att10 { get; set; }
        public string Att11 { get; set; }
        public string Att12 { get; set; }
        public string Att13 { get; set; }
        public string Att14 { get; set; }
        public string Att15 { get; set; }
        public string Att16 { get; set; }
        public string Att17 { get; set; }
        public string Att18 { get; set; }
        public string Att19 { get; set; }
        public string Att20 { get; set; }
        public string HsCode { get; set; }
        public string UomBase { get; set; }
        public Nullable<int> QtyLooseBase { get; set; }
        public string Arcode { get; set; }
        public string ApCode { get; set; }
        public Nullable<int> MinOrderQty { get; set; }
        public Nullable<int> NewOrderQty { get; set; }
        public string StorageType { get; set; }
        public string StorageTemp { get; set; }
        public string OptionType { get; set; }
        public string PartNo { get; set; }
    }
}
