//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_rpt
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public string RefType { get; set; }
        public string ProcName { get; set; }
        public Nullable<bool> IsBatch { get; set; }
        public string BatchSQL { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public string CheckSQL { get; set; }
        public string Value1 { get; set; }
        public string Value2 { get; set; }
        public string RepxName1 { get; set; }
        public string RepxName2 { get; set; }
        public string SubPath { get; set; }
        public string SubProcName { get; set; }
    }
}
