//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_alert
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string JobNo { get; set; }
        public string JobType { get; set; }
        public string DocNo { get; set; }
        public string DocType { get; set; }
        public string SendType { get; set; }
        public string SendMethod { get; set; }
        public string SendFrom { get; set; }
        public string SendTo { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public string StatusCode { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string AlertType { get; set; }
    }
}
