//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPT_Job
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string JobType { get; set; }
        public string JobProgress { get; set; }
        public Nullable<System.DateTime> JobDate { get; set; }
        public string JobPic { get; set; }
        public string JobLevel { get; set; }
        public string JobRmk { get; set; }
        public string CustRef { get; set; }
        public Nullable<decimal> Wt { get; set; }
        public Nullable<decimal> M3 { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PkgType { get; set; }
        public string BlRef { get; set; }
        public string BkgRef { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public string FinDest { get; set; }
        public Nullable<System.DateTime> Eta { get; set; }
        public Nullable<System.DateTime> Etd { get; set; }
        public string Driver { get; set; }
        public string Term { get; set; }
        public string PickFrm1 { get; set; }
        public string PickFrm2 { get; set; }
        public string DeliveryTo1 { get; set; }
        public string DeliveryTo2 { get; set; }
        public string InvoiceNo { get; set; }
        public string CnNo { get; set; }
        public string VoucherNo { get; set; }
        public string MasterRef { get; set; }
        public string HouseRef { get; set; }
        public string JobCode { get; set; }
        public string JobCodeRmk { get; set; }
        public string CargoMkg { get; set; }
        public string CargoDesc { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public string Cust { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string VehicleType { get; set; }
        public string SoKey { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<System.DateTime> ArriveDate { get; set; }
        public string CloseInd { get; set; }
        public string StatusCode { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string TptType { get; set; }
        public string CustPic { get; set; }
        public string CustContact { get; set; }
        public string CustEmail { get; set; }
        public string CustDocNo { get; set; }
        public string CustDocType { get; set; }
        public Nullable<System.DateTime> BkgDate { get; set; }
        public string BkgTime { get; set; }
        public Nullable<decimal> BkgWt { get; set; }
        public Nullable<decimal> BkgM3 { get; set; }
        public Nullable<int> BkgQty { get; set; }
        public string BkgPkgType { get; set; }
        public Nullable<decimal> FeeTpt { get; set; }
        public Nullable<decimal> FeeLabour { get; set; }
        public Nullable<decimal> FeeOt { get; set; }
        public Nullable<decimal> FeeAdmin { get; set; }
        public Nullable<decimal> FeeReimberse { get; set; }
        public Nullable<decimal> FeeMisc { get; set; }
        public Nullable<decimal> FeeTotal { get; set; }
        public string FeeRemark { get; set; }
        public string TripCode { get; set; }
        public Nullable<System.DateTime> TptDate { get; set; }
        public string TptTime { get; set; }
    }
}
