//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_assign
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> user_assign_id { get; set; }
        public Nullable<System.DateTime> time_start { get; set; }
        public Nullable<System.DateTime> time_end { get; set; }
        public string access_level { get; set; }
        public string status_code { get; set; }
        public string remark { get; set; }
    }
}
