//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_ContractDet
    {
        public int Id { get; set; }
        public string ContractNo { get; set; }
        public string ProductCode { get; set; }
        public Nullable<bool> IsFixed { get; set; }
        public Nullable<bool> IsYearly { get; set; }
        public Nullable<decimal> YearlyFee { get; set; }
        public Nullable<bool> IsMonthly { get; set; }
        public Nullable<decimal> MonthlyFee { get; set; }
        public Nullable<bool> IsWeekly { get; set; }
        public Nullable<decimal> WeeklyFee { get; set; }
        public Nullable<bool> IsDaily { get; set; }
        public Nullable<int> DailyNo { get; set; }
        public Nullable<decimal> DailyFee { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Price3 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public string ProductClass { get; set; }
        public Nullable<decimal> HandlingFee { get; set; }
        public Nullable<decimal> StorageFee { get; set; }
        public string ChgCode { get; set; }
        public string Unit { get; set; }
        public string StorageType { get; set; }
        public string ChgDes { get; set; }
        public Nullable<bool> Palletized { get; set; }
    }
}
