//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wh_DoDet3
    {
        public int Id { get; set; }
        public string DoNo { get; set; }
        public string DoType { get; set; }
        public string ContainerNo { get; set; }
        public string SealNo { get; set; }
        public string ContainerType { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> M3 { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PkgType { get; set; }
        public string RelaId { get; set; }
        public string ContainerStatus { get; set; }
        public Nullable<System.DateTime> JobStart { get; set; }
        public Nullable<System.DateTime> JobEnd { get; set; }
    }
}
