//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_InventoryDet
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string InventoryNo { get; set; }
        public Nullable<int> LineINo { get; set; }
        public string Product { get; set; }
        public string WarehouseId { get; set; }
        public string LocId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> AdjustQty { get; set; }
        public string Unit { get; set; }
        public string LotNo { get; set; }
        public string BatchNo { get; set; }
        public string CustomsLotNo { get; set; }
        public Nullable<int> Qty1 { get; set; }
        public Nullable<int> Qty2 { get; set; }
        public Nullable<int> Qty3 { get; set; }
        public string Uom1 { get; set; }
        public string Uom2 { get; set; }
        public string Uom3 { get; set; }
        public Nullable<int> QtyPackWhole { get; set; }
        public Nullable<int> QtyWholeLoose { get; set; }
    }
}
