//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XXChartAcc
    {
        public int SequenceId { get; set; }
        public string Code { get; set; }
        public string AcDesc { get; set; }
        public string AcType { get; set; }
        public string AcDorc { get; set; }
        public string AcBank { get; set; }
        public string AcCurrency { get; set; }
        public string AcSubType { get; set; }
        public string AcSubPl { get; set; }
        public string AcSubBl { get; set; }
        public string GNo { get; set; }
        public string GCode { get; set; }
    }
}
