//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class XXSetup
    {
        public int SequenceId { get; set; }
        public string Category { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Description { get; set; }
        public Nullable<int> Year { get; set; }
        public string Prefix { get; set; }
        public string Suffix { get; set; }
    }
}
