//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_data2
    {
        public int Id { get; set; }
        public string sys_jobtype { get; set; }
        public string sys_triptype { get; set; }
        public string sys_triptype2 { get; set; }
        public Nullable<System.DateTime> sys_date { get; set; }
        public string info_jobno { get; set; }
        public string info_jobno2 { get; set; }
        public string info_orderby { get; set; }
        public string info_leg { get; set; }
        public string info_tasktype { get; set; }
        public string info_pickupdate { get; set; }
        public string info_pickuptime { get; set; }
        public string info_vehicle { get; set; }
        public string info_trailer { get; set; }
        public string info_incentive { get; set; }
        public string info_client { get; set; }
        public string info_clientref { get; set; }
        public string info_dono { get; set; }
        public string info_contno { get; set; }
        public string info_sealno { get; set; }
        public string info_from { get; set; }
        public string info_to { get; set; }
        public string info_contremark { get; set; }
        public string info_opcode { get; set; }
        public string info_vessel { get; set; }
        public string info_etadate { get; set; }
        public string info_etatime { get; set; }
        public string info_permit { get; set; }
        public string info_tripremark { get; set; }
        public string info_product { get; set; }
        public string info_desc { get; set; }
        public Nullable<decimal> info_qty { get; set; }
        public string info_uom { get; set; }
    }
}
