//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_data_mita_code
    {
        public int Id { get; set; }
        public string info_code { get; set; }
        public string info_att6 { get; set; }
        public string info_att5 { get; set; }
        public string info_att4 { get; set; }
        public string info_att3 { get; set; }
        public string info_att2 { get; set; }
        public string info_att1 { get; set; }
        public string info_group { get; set; }
        public string info_desc { get; set; }
    }
}
