//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class air_ref
    {
        public int Id { get; set; }
        public string RefType { get; set; }
        public string MAWB { get; set; }
        public string RefNo { get; set; }
        public string AgentId { get; set; }
        public string NvoccAgentId { get; set; }
        public string CarrierAgentId { get; set; }
        public string CarrierBkgNo { get; set; }
        public string NvoccBlNO { get; set; }
        public string WareHouseId { get; set; }
        public string AirportCode0 { get; set; }
        public string AirportName0 { get; set; }
        public string AirportCode1 { get; set; }
        public string AirportName1 { get; set; }
        public Nullable<System.DateTime> FlightDate0 { get; set; }
        public string FlightTime0 { get; set; }
        public Nullable<System.DateTime> FlightDate1 { get; set; }
        public string FlightTime1 { get; set; }
        public string AirlineCode1 { get; set; }
        public string AirlineName1 { get; set; }
        public string FlightNo1 { get; set; }
        public string AirlineCode2 { get; set; }
        public string AirlineName2 { get; set; }
        public string FlightNo2 { get; set; }
        public Nullable<System.DateTime> FlightDate2 { get; set; }
        public string FlightTime2 { get; set; }
        public string AirportCode2 { get; set; }
        public string AirportName2 { get; set; }
        public string AirlineCode3 { get; set; }
        public string AirlineName3 { get; set; }
        public string FlightNo3 { get; set; }
        public Nullable<System.DateTime> FlightDate3 { get; set; }
        public string FlightTime3 { get; set; }
        public string AirportCode3 { get; set; }
        public string AirportName3 { get; set; }
        public string AirlineCode4 { get; set; }
        public string AirlineName4 { get; set; }
        public string FlightNo4 { get; set; }
        public Nullable<System.DateTime> FlightDate4 { get; set; }
        public string FlightTime4 { get; set; }
        public string AirportCode4 { get; set; }
        public string AirportName4 { get; set; }
        public string IssuedBy { get; set; }
        public string ShipperID { get; set; }
        public string ShipperName { get; set; }
        public string ConsigneeID { get; set; }
        public string ConsigneeName { get; set; }
        public string CarrierAgent { get; set; }
        public string AccountInfo { get; set; }
        public string AgentIATACode { get; set; }
        public string AgentAccountNo { get; set; }
        public string AirportDeparture { get; set; }
        public string ConnDest1 { get; set; }
        public string ConnCarrier1 { get; set; }
        public string ConnDest2 { get; set; }
        public string ConnCarrier2 { get; set; }
        public string ConnDest3 { get; set; }
        public string ConnCarrier3 { get; set; }
        public string AirportDestination { get; set; }
        public string RequestedFlight { get; set; }
        public string RequestedDate { get; set; }
        public string Currency { get; set; }
        public string ChgsCode { get; set; }
        public string PPD1 { get; set; }
        public string COLL1 { get; set; }
        public string PPD2 { get; set; }
        public string COLL2 { get; set; }
        public string CarriageValue { get; set; }
        public string CustomValue { get; set; }
        public string AmountInsurance { get; set; }
        public string HandlingInfo { get; set; }
        public string Piece { get; set; }
        public string GrossWeight { get; set; }
        public string Unit { get; set; }
        public string RateClass { get; set; }
        public string CommodityItemNo { get; set; }
        public string ChargeableWeight { get; set; }
        public string RateCharge { get; set; }
        public string Total { get; set; }
        public string GoodsNature { get; set; }
        public string ContentRemark { get; set; }
        public string WeightChargeP { get; set; }
        public string ValuationChargeP { get; set; }
        public string WeightChargeC { get; set; }
        public string ValuationChargeC { get; set; }
        public string TaxP { get; set; }
        public string TaxC { get; set; }
        public string OtherAgentChargeP { get; set; }
        public string OtherAgentChargeC { get; set; }
        public string OtherCarrierChargeP { get; set; }
        public string OtherCarrierChargeC { get; set; }
        public string TotalPrepaid { get; set; }
        public string TotalCollect { get; set; }
        public string CurrencyRate { get; set; }
        public string ChargeDestCurrency { get; set; }
        public string OtherCharge1 { get; set; }
        public string OtherCharge2 { get; set; }
        public string OtherCharge3 { get; set; }
        public string SignatureShipper { get; set; }
        public string ExecuteDate { get; set; }
        public string ExecutePlace { get; set; }
        public string SignatureIssuing { get; set; }
        public string OtherCharge4 { get; set; }
        public string OtherCharge5 { get; set; }
        public string OtherCharge1Currency { get; set; }
        public string OtherCharge2Currency { get; set; }
        public string OtherCharge3Currency { get; set; }
        public string OtherCharge4Currency { get; set; }
        public string OtherCharge5Currency { get; set; }
        public Nullable<decimal> OtherCharge1Amount { get; set; }
        public Nullable<decimal> OtherCharge2Amount { get; set; }
        public Nullable<decimal> OtherCharge3Amount { get; set; }
        public Nullable<decimal> OtherCharge4Amount { get; set; }
        public Nullable<decimal> OtherCharge5Amount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string CloseInd { get; set; }
        public string CloseUser { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public Nullable<System.DateTime> AirFlightDate1 { get; set; }
        public string AirFlightTime1 { get; set; }
        public string AirLinePortCode1 { get; set; }
        public string AirLinePortName1 { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string LocalCust { get; set; }
        public string remark { get; set; }
        public Nullable<decimal> EstSaleAmt { get; set; }
        public Nullable<decimal> EstCostAmt { get; set; }
        public string Remarks { get; set; }
        public string StatusCode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> ExRate { get; set; }
    }
}
