//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cms_menu
    {
        public int SequenceId { get; set; }
        public int ParentId { get; set; }
        public string Name { get; set; }
        public string Note { get; set; }
        public string Color { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Link { get; set; }
        public string LinkType { get; set; }
        public string RoleAllow { get; set; }
        public string UserDeny { get; set; }
        public string Status { get; set; }
        public string IpAccess { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public string RoleName { get; set; }
        public Nullable<int> MastId { get; set; }
    }
}
