//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont_Asset
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string DocNo { get; set; }
        public string DocType { get; set; }
        public string JobNo { get; set; }
        public string DepotCode { get; set; }
        public string ShipType { get; set; }
        public string ShipVessel { get; set; }
        public string ShipVoyage { get; set; }
        public string ShipPol { get; set; }
        public string ShipPod { get; set; }
        public string ShipFinDest { get; set; }
        public Nullable<System.DateTime> ShipEta { get; set; }
        public Nullable<System.DateTime> ShipEtd { get; set; }
        public string ShipNote { get; set; }
        public string ShipCarrierCode { get; set; }
        public string ShipCarrierRef { get; set; }
        public string DemurrageCode { get; set; }
        public Nullable<int> DemurrageFreeDay { get; set; }
        public Nullable<System.DateTime> DemurrageStartDate { get; set; }
        public string DemurrageRef { get; set; }
        public string DetentionCode { get; set; }
        public Nullable<int> DetentionFreeDay { get; set; }
        public Nullable<System.DateTime> DetentionStartDate { get; set; }
        public string DetentionRef { get; set; }
        public string ReleaseType { get; set; }
        public string ReturnType { get; set; }
        public string ShipperCode { get; set; }
        public string ShipperName { get; set; }
        public string ConsigneeCode { get; set; }
        public string ConsigneeName { get; set; }
        public string Instruction { get; set; }
        public string HaulierCode { get; set; }
        public string HaulierRef { get; set; }
        public Nullable<System.DateTime> HaulierCompleteDate { get; set; }
        public string StatusCode { get; set; }
    }
}
