//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cost
    {
        public int SequenceId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> CostIndex { get; set; }
        public string RefNo { get; set; }
        public string JobNo { get; set; }
        public string RefType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Marking { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> Profitmargin { get; set; }
        public Nullable<decimal> ExRate1 { get; set; }
        public Nullable<decimal> ExRate2 { get; set; }
        public Nullable<decimal> ExRate3 { get; set; }
        public Nullable<decimal> ExRate4 { get; set; }
        public Nullable<decimal> Amt1 { get; set; }
        public Nullable<decimal> Amt2 { get; set; }
        public Nullable<decimal> Amt3 { get; set; }
        public Nullable<decimal> Amt4 { get; set; }
        public string Curr1 { get; set; }
        public string Curr2 { get; set; }
        public string Curr3 { get; set; }
        public string Curr4 { get; set; }
        public Nullable<decimal> Value0 { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public Nullable<decimal> Value4 { get; set; }
        public Nullable<decimal> Value5 { get; set; }
        public Nullable<decimal> Value6 { get; set; }
        public Nullable<decimal> Value7 { get; set; }
        public Nullable<decimal> Value8 { get; set; }
    }
}
