//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctm_driver
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string ICNo { get; set; }
        public string Attendant { get; set; }
        public string Remark { get; set; }
        public string Isstaff { get; set; }
        public string TowheaderCode { get; set; }
        public string ServiceLevel { get; set; }
        public string StatusCode { get; set; }
        public string TeamNo { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseExpiry { get; set; }
        public string BankAccount { get; set; }
        public Nullable<decimal> SalaryBasic { get; set; }
        public Nullable<decimal> SalaryAllowance { get; set; }
        public string SalaryRemark { get; set; }
        public string SubContract_Ind { get; set; }
    }
}
