//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_JobDet1
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string EdiNo { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerType { get; set; }
        public string SealNo { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> QTY { get; set; }
        public string PackageType { get; set; }
        public string DgClass { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> CfsInDate { get; set; }
        public Nullable<System.DateTime> CfsOutDate { get; set; }
        public Nullable<System.DateTime> YardPickupDate { get; set; }
        public Nullable<System.DateTime> YardReturnDate { get; set; }
        public string PortnetStatus { get; set; }
        public string F5Ind { get; set; }
        public string UrgentInd { get; set; }
        public string Remark { get; set; }
        public string StatusCode { get; set; }
        public Nullable<System.DateTime> CdtDate { get; set; }
        public string CdtTime { get; set; }
        public string TerminalLocation { get; set; }
        public Nullable<System.DateTime> YardExpiryDate { get; set; }
        public string YardExpiryTime { get; set; }
        public string YardAddress { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Permit { get; set; }
        public string TTTime { get; set; }
        public string WarehouseStatus { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public string Status4 { get; set; }
        public string Status5 { get; set; }
        public string Status6 { get; set; }
        public string Status7 { get; set; }
        public string Status8 { get; set; }
        public string BR { get; set; }
        public string EmailInd { get; set; }
        public string KdydInd { get; set; }
        public string BillType { get; set; }
        public string CfsStatus { get; set; }
        public string oogInd { get; set; }
        public string dischargeCell { get; set; }
        public Nullable<System.DateTime> ScheduleStartDate { get; set; }
        public string ScheduleStartTime { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public string CompletionTime { get; set; }
        public Nullable<System.DateTime> UnStaffDate { get; set; }
        public Nullable<System.DateTime> StaffDate { get; set; }
        public Nullable<System.DateTime> StuffingDate { get; set; }
        public Nullable<System.DateTime> UnStuffingDate { get; set; }
        public string ContainerCategory { get; set; }
        public Nullable<System.DateTime> CustomsClearDate { get; set; }
        public string CustomsClearStatus { get; set; }
        public string CustomsVerifyInd { get; set; }
        public Nullable<System.DateTime> CustomsVerifyDate { get; set; }
        public string CustomsRemark { get; set; }
        public string VehicleType { get; set; }
        public string SubContract_Ind { get; set; }
        public string Contractor { get; set; }
        public string JobType { get; set; }
        public string DepotBkgRefNo { get; set; }
        public string Stuff_Ind { get; set; }
        public string PermitNo { get; set; }
        public Nullable<System.DateTime> PermitDate { get; set; }
        public string PermitBy { get; set; }
        public string PermitRemark { get; set; }
        public string PartyInvNo { get; set; }
        public Nullable<decimal> GstAmt { get; set; }
        public string PaymentStatus { get; set; }
        public string IncoTerms { get; set; }
        public string ReturnLastDate { get; set; }
        public string WhsReadyInd { get; set; }
        public string WhsReadyTime { get; set; }
        public string WhsReadyLocation { get; set; }
        public Nullable<decimal> WhsReadyWeight { get; set; }
        public string ReleaseToHaulierRemark { get; set; }
        public string ScheduleTime { get; set; }
        public Nullable<int> JobId { get; set; }
        public string ServiceType { get; set; }
        public Nullable<decimal> ContWeight { get; set; }
        public Nullable<decimal> CargoWeight { get; set; }
    }
}
