//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Person
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string IcNo { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public string Race { get; set; }
        public string Religion { get; set; }
        public string Married { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string Remark3 { get; set; }
        public string Remark4 { get; set; }
        public string Status { get; set; }
        public string Department { get; set; }
        public string HrRole { get; set; }
        public string RecruitId { get; set; }
        public string InterviewId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string StatusCode { get; set; }
        public string Remark5 { get; set; }
        public string HrGroup { get; set; }
        public string PassType { get; set; }
        public string PassNo { get; set; }
        public string Dialect { get; set; }
        public string LanguageWrittenRemark { get; set; }
        public string LanguageSpokenRemark { get; set; }
        public string NationalServiceStatus { get; set; }
        public string NationalServiceRemark { get; set; }
        public string EmploySource { get; set; }
        public string EmploySourceRemark { get; set; }
        public string DrivingType { get; set; }
        public string DrivingRemark { get; set; }
        public string HealthStatus { get; set; }
        public string HealthRemark { get; set; }
        public string OverTimeStatus { get; set; }
        public string OverTimeRemark { get; set; }
        public string RelativeWorkingStatus { get; set; }
        public string RelativeWorkingRemark { get; set; }
        public string TerminateStatus { get; set; }
        public string TerminateRemark { get; set; }
        public string CheckReferenceStatus { get; set; }
        public string CheckReferenceRemark { get; set; }
        public string EmploymentType { get; set; }
        public string SalaryPaymode { get; set; }
        public Nullable<int> HoursPerDay { get; set; }
        public Nullable<int> HoursPerWeek { get; set; }
        public Nullable<int> HoursPerMonth { get; set; }
        public Nullable<int> DaysPerWeek { get; set; }
        public Nullable<int> DaysPerMonth { get; set; }
        public Nullable<System.DateTime> ProbationFromDate { get; set; }
        public Nullable<System.DateTime> ProbationToDate { get; set; }
        public Nullable<decimal> StartSalary { get; set; }
        public string PRInd { get; set; }
        public Nullable<int> PRYear { get; set; }
        public Nullable<decimal> Wage { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Overtime { get; set; }
        public Nullable<decimal> Amount1 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> Amount3 { get; set; }
        public Nullable<decimal> Amount4 { get; set; }
        public Nullable<decimal> Amount5 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public string Status4 { get; set; }
        public string Status5 { get; set; }
        public string Status6 { get; set; }
        public string Status7 { get; set; }
        public string Status8 { get; set; }
        public string IsCPF { get; set; }
    }
}
