//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_receipt
    {
        public int Id { get; set; }
        public Nullable<int> TrailerId { get; set; }
        public string TrailerNo { get; set; }
        public Nullable<int> CargoId { get; set; }
        public string JobNo { get; set; }
        public Nullable<int> LineId { get; set; }
        public string BookingNo { get; set; }
        public string HblNo { get; set; }
        public string SkuCode { get; set; }
        public string UomCode { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> PackQty { get; set; }
        public string Location { get; set; }
        public string CargoType { get; set; }
        public string Marking1 { get; set; }
        public string Marking2 { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
    }
}
