//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobItem
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string ItemType { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> ItemQty { get; set; }
        public Nullable<decimal> ItemValue { get; set; }
        public string ItemMark { get; set; }
        public string ItemNote { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string IsFlat { get; set; }
    }
}
