//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobInventory
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public string ItemNo { get; set; }
        public string Description { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Unit { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<System.DateTime> DoDate { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string DoType { get; set; }
        public string PalletNo { get; set; }
        public string Location { get; set; }
        public Nullable<int> BalQty { get; set; }
        public string RelaId { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Note5 { get; set; }
        public string Note6 { get; set; }
        public string Note7 { get; set; }
        public string Note8 { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public string Status4 { get; set; }
        public string Status5 { get; set; }
        public string Status6 { get; set; }
        public string Status7 { get; set; }
        public string Status8 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
    }
}
