//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobTask
    {
        public int SequenceId { get; set; }
        public string RefNo { get; set; }
        public string JobNo { get; set; }
        public string ChgCode { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<bool> PrintInd { get; set; }
        public string WtEntryInd { get; set; }
        public string PrintTerm { get; set; }
    }
}
