//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Container
    {
        public int Id { get; set; }
        public string ContainerNo { get; set; }
        public Nullable<System.DateTime> CommDate { get; set; }
        public string TankCat { get; set; }
        public string Lessor { get; set; }
        public Nullable<System.DateTime> ManuDate { get; set; }
        public string Manufacturer { get; set; }
        public string PlateNo { get; set; }
        public string ContainerType { get; set; }
        public Nullable<decimal> ExternalLength { get; set; }
        public Nullable<decimal> ExternalBreadth { get; set; }
        public Nullable<decimal> ExternalHeight { get; set; }
        public Nullable<decimal> InternalLength { get; set; }
        public Nullable<decimal> InternalBreadth { get; set; }
        public Nullable<decimal> InternalHeight { get; set; }
        public string Material { get; set; }
        public string ExternalCoat { get; set; }
        public Nullable<decimal> Capacity { get; set; }
        public Nullable<decimal> MaxGrossWeight { get; set; }
        public Nullable<decimal> TareWeight { get; set; }
        public Nullable<decimal> MaxPayload { get; set; }
        public Nullable<decimal> TestPress { get; set; }
        public Nullable<decimal> Thickness { get; set; }
        public string Approvals { get; set; }
        public Nullable<System.DateTime> OnHireDateTime { get; set; }
        public Nullable<System.DateTime> OffHireDateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string StatusCode { get; set; }
    }
}
