//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_Vehicle
    {
        public int Id { get; set; }
        public string VehicleCode { get; set; }
        public string VehicleType { get; set; }
        public string VehicleStatus { get; set; }
        public string ContractNo { get; set; }
        public string ContractType { get; set; }
        public Nullable<System.DateTime> ContractDate { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public string LicenseNo { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string SupplierCode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> InsuranceExpiryDate { get; set; }
        public Nullable<System.DateTime> RoadTaxExpiryDate { get; set; }
        public Nullable<System.DateTime> CraneLGCertExpiryDate { get; set; }
        public Nullable<System.DateTime> CraneLHCertExpiryDate { get; set; }
        public Nullable<System.DateTime> VpcExpiryDate { get; set; }
        public Nullable<System.DateTime> LastInternalInspectionDate { get; set; }
        public string VeicleSize { get; set; }
        public string VehicleUse { get; set; }
    }
}
