//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_DriverCash
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public string EventType { get; set; }
        public Nullable<System.DateTime> EventExpiryDate { get; set; }
        public string Description { get; set; }
        public string DriverCode { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string StaffCode { get; set; }
        public string DocNo { get; set; }
        public Nullable<decimal> DocAmt { get; set; }
        public string Remark { get; set; }
        public string JobNo { get; set; }
        public string ContNo { get; set; }
        public string TripNo { get; set; }
        public string TripType { get; set; }
    }
}
