//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaExport
    {
        public int SequenceId { get; set; }
        public string RefNo { get; set; }
        public string ContainerNo { get; set; }
        public string JobNo { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string HblNo { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string FrtTerm { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public string PlaceDeliveryId { get; set; }
        public string PlaceDeliveryname { get; set; }
        public string PlaceReceiveId { get; set; }
        public string PlaceReceiveName { get; set; }
        public string PlaceDeliveryTerm { get; set; }
        public string PlaceReceiveTerm { get; set; }
        public string PreCarriage { get; set; }
        public string ShipOnBoardInd { get; set; }
        public Nullable<System.DateTime> ShipOnBoardDate { get; set; }
        public string ShipLoadInd { get; set; }
        public string ExpressBl { get; set; }
        public string TsInd { get; set; }
        public string TsJobNo { get; set; }
        public string PermitRmk { get; set; }
        public string SShipperRemark { get; set; }
        public string SAgentRemark { get; set; }
        public string SConsigneeRemark { get; set; }
        public string SNotifyPartyRemark { get; set; }
        public Nullable<decimal> ImpCharge { get; set; }
        public string HaulierName { get; set; }
        public string HaulierCrNo { get; set; }
        public string HaulierAttention { get; set; }
        public string HaulierCollect { get; set; }
        public string HaulierTruck { get; set; }
        public Nullable<System.DateTime> HaulierCollectDate { get; set; }
        public string HaulierRemark { get; set; }
        public string HaulierPkgType { get; set; }
        public Nullable<int> HaulierQty { get; set; }
        public Nullable<decimal> HaulierWt { get; set; }
        public Nullable<decimal> HaulierM3 { get; set; }
        public string placeLoadingName { get; set; }
        public string placeDischargeName { get; set; }
        public string clauseFreightTerm { get; set; }
        public string clauseBL { get; set; }
        public string clauseCargo { get; set; }
        public string SurrenderBl { get; set; }
        public string BkgRefNo { get; set; }
        public string FinDest { get; set; }
        public string ShipperId { get; set; }
        public string ShipperName { get; set; }
        public string ShipperContact { get; set; }
        public string ShipperTel { get; set; }
        public string ShipperFax { get; set; }
        public string ShipperEmail { get; set; }
        public string AsAgent { get; set; }
        public string Remark { get; set; }
        public string Marking { get; set; }
        public string CollectFrom { get; set; }
        public string CancelInd { get; set; }
        public string CancelRmk { get; set; }
        public string CancelUser { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string StatusCode { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string QuoteNo { get; set; }
        public string PoNo { get; set; }
        public string ValueCurrency { get; set; }
        public Nullable<decimal> ValueExRate { get; set; }
        public Nullable<decimal> ValueAmt { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public string DriverLicense { get; set; }
        public string DriverRemark { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public Nullable<System.DateTime> PODTime { get; set; }
        public string PODBy { get; set; }
        public string PODRemark { get; set; }
        public string PODUpdateUser { get; set; }
        public Nullable<System.DateTime> PODUpdateTime { get; set; }
        public string Dept { get; set; }
        public string HaulierCollectTime { get; set; }
        public string HaulierDeliveryTime { get; set; }
        public Nullable<System.DateTime> HaulierDeliveryDate { get; set; }
        public string HaulierSendTo { get; set; }
        public string HaulierStuffBy { get; set; }
        public string HaulierCoload { get; set; }
        public string HaulierPerson { get; set; }
        public string HaulierPersonTel { get; set; }
        public string DgCategory { get; set; }
        public string DgImdgClass { get; set; }
        public string DgUnNo { get; set; }
        public string DgShippingName { get; set; }
        public string DgTecnicalName { get; set; }
        public string DgMfagNo1 { get; set; }
        public string DgMfagNo2 { get; set; }
        public string DgEmsFire { get; set; }
        public string DgEmsSpill { get; set; }
        public string DgLimitedQtyInd { get; set; }
        public string DgExemptedQtyInd { get; set; }
        public string DgNetWeight { get; set; }
        public string DgFlashPoint { get; set; }
        public string DgRadio { get; set; }
        public string DgPageNo { get; set; }
        public string DgPackingGroup { get; set; }
        public string DgPackingTypeCode { get; set; }
        public string DgTransportCode { get; set; }
        public string HaulierFax { get; set; }
    }
}
