//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaImport
    {
        public int SequenceId { get; set; }
        public string RefNo { get; set; }
        public string ContainerNo { get; set; }
        public string JobNo { get; set; }
        public string HblNo { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string ExpressBl { get; set; }
        public string TruckingInd { get; set; }
        public string Shipper { get; set; }
        public string Consignee { get; set; }
        public string DoRealeaseTo { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DoReadyInd { get; set; }
        public string ForwardingId { get; set; }
        public string FrCollectInd { get; set; }
        public Nullable<decimal> CollectAmount { get; set; }
        public string CollectCurrency { get; set; }
        public Nullable<decimal> CollectExRate { get; set; }
        public string TsInd { get; set; }
        public string TsSchNo { get; set; }
        public string TsBkgId { get; set; }
        public string TsBkgNo { get; set; }
        public string TsRefNo { get; set; }
        public string TsJobNo { get; set; }
        public string TsPod { get; set; }
        public string TsPortFinName { get; set; }
        public string TsVessel { get; set; }
        public string TsVoyage { get; set; }
        public string TsColoader { get; set; }
        public Nullable<System.DateTime> TsEtd { get; set; }
        public Nullable<System.DateTime> TsEta { get; set; }
        public string TsAgentId { get; set; }
        public string TsRemark { get; set; }
        public Nullable<decimal> TsAgtRate { get; set; }
        public Nullable<decimal> TsTotAgtRate { get; set; }
        public Nullable<decimal> TsImpRate { get; set; }
        public Nullable<decimal> TsTotImpRate { get; set; }
        public string PermitRmk { get; set; }
        public string SShipperRemark { get; set; }
        public string SAgentRemark { get; set; }
        public string SConsigneeRemark { get; set; }
        public string SNotifyPartyRemark { get; set; }
        public Nullable<decimal> rateForklift { get; set; }
        public Nullable<decimal> rateProcess { get; set; }
        public Nullable<decimal> rateTracing { get; set; }
        public Nullable<decimal> rateWarehouse { get; set; }
        public Nullable<decimal> rateAdmin { get; set; }
        public string flagNomination { get; set; }
        public string CltFrmId { get; set; }
        public string DeliveryToId { get; set; }
        public Nullable<System.DateTime> CltDoDate { get; set; }
        public string CustomerName { get; set; }
        public string ValueCurrency { get; set; }
        public Nullable<decimal> ValueExRate { get; set; }
        public Nullable<decimal> ValueAmt { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public string DriverLicense { get; set; }
        public string DriverRemark { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string HaulierName { get; set; }
        public string HaulierCrNo { get; set; }
        public string HaulierAttention { get; set; }
        public string HaulierCollect { get; set; }
        public string HaulierTruck { get; set; }
        public Nullable<System.DateTime> HaulierCollectDate { get; set; }
        public string HaulierRemark { get; set; }
        public Nullable<System.DateTime> PODTime { get; set; }
        public string PODBy { get; set; }
        public string PODRemark { get; set; }
        public string PODUpdateUser { get; set; }
        public Nullable<System.DateTime> PODUpdateTime { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string StatusCode { get; set; }
        public string Remark { get; set; }
        public string GstPermitNo { get; set; }
        public Nullable<decimal> GstPaidAmt { get; set; }
        public string Dept { get; set; }
        public string HaulierCollectTime { get; set; }
        public string HaulierDeliveryTime { get; set; }
        public Nullable<System.DateTime> HaulierDeliveryDate { get; set; }
        public string HaulierSendTo { get; set; }
        public string HaulierStuffBy { get; set; }
        public string HaulierCoload { get; set; }
        public string HaulierPerson { get; set; }
        public string HaulierPersonTel { get; set; }
        public string DgCategory { get; set; }
        public string DgImdgClass { get; set; }
        public string DgUnNo { get; set; }
        public string DgShippingName { get; set; }
        public string DgTecnicalName { get; set; }
        public string DgMfagNo1 { get; set; }
        public string DgMfagNo2 { get; set; }
        public string DgEmsFire { get; set; }
        public string DgEmsSpill { get; set; }
        public string DgLimitedQtyInd { get; set; }
        public string DgExemptedQtyInd { get; set; }
        public string DgNetWeight { get; set; }
        public string DgFlashPoint { get; set; }
        public string DgRadio { get; set; }
        public string DgPageNo { get; set; }
        public string DgPackingGroup { get; set; }
        public string DgPackingTypeCode { get; set; }
        public string DgTransportCode { get; set; }
        public string HaulierFax { get; set; }
    }
}
