//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaImportRef
    {
        public int SequenceId { get; set; }
        public string RefNo { get; set; }
        public string JobType { get; set; }
        public string AgentId { get; set; }
        public string CrAgentId { get; set; }
        public string WarehouseId { get; set; }
        public string NvoccAgentId { get; set; }
        public string NvoccBl { get; set; }
        public string ForwardAgentId { get; set; }
        public string TransportId { get; set; }
        public string OblNo { get; set; }
        public string CrBkgNo { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public Nullable<System.DateTime> Eta { get; set; }
        public Nullable<System.DateTime> Etd { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string StatusCode { get; set; }
        public string SShipperRemark { get; set; }
        public string SAgentRemark { get; set; }
        public string SConsigneeRemark { get; set; }
        public string SNotifyPartyRemark { get; set; }
        public string HaulierName { get; set; }
        public string HaulierCrNo { get; set; }
        public string HaulierAttention { get; set; }
        public string HaulierCollect { get; set; }
        public string HaulierTruck { get; set; }
        public Nullable<System.DateTime> HaulierCollectDate { get; set; }
        public string HaulierRemark { get; set; }
        public string PermitRemark { get; set; }
        public string Remark { get; set; }
        public Nullable<int> HaulierQty { get; set; }
        public string HaulierPkgType { get; set; }
        public Nullable<decimal> HaulierWt { get; set; }
        public Nullable<decimal> HaulierM3 { get; set; }
        public string RefType { get; set; }
        public Nullable<decimal> EstSaleAmt { get; set; }
        public Nullable<decimal> EstCostAmt { get; set; }
        public string LocalCust { get; set; }
        public Nullable<System.DateTime> RefDate { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string HaulierFax { get; set; }
        public string DriverName { get; set; }
        public string DriverMobile { get; set; }
        public string DriverLicense { get; set; }
        public string VehicleNo { get; set; }
        public string VehicleType { get; set; }
        public string DriverRemark { get; set; }
        public string HaulierCollectTime { get; set; }
        public string HaulierDeliveryTime { get; set; }
        public string HaulierSendTo { get; set; }
        public string HaulierStuffBy { get; set; }
        public string HaulierCoload { get; set; }
        public string HaulierPerson { get; set; }
        public string HaulierPersonTel { get; set; }
        public string PermitRmk { get; set; }
        public Nullable<System.DateTime> HaulierDeliveryDate { get; set; }
        public string PoNo { get; set; }
    }
}
