//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaQuoteDet
    {
        public int SequenceId { get; set; }
        public Nullable<int> DocId { get; set; }
        public Nullable<int> DocLineNo { get; set; }
        public string ChgCode { get; set; }
        public string ChgDes1 { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Price20 { get; set; }
        public Nullable<decimal> Price40 { get; set; }
        public string Unit { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public string GstType { get; set; }
        public Nullable<decimal> PriceLcl { get; set; }
        public string JobType { get; set; }
        public string Port1 { get; set; }
        public string Port2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<int> PrintOrder { get; set; }
    }
}
