//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaQuote
    {
        public int SequenceId { get; set; }
        public string JobType { get; set; }
        public string ImpExpInd { get; set; }
        public string DocNo { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<System.DateTime> DocFromDate { get; set; }
        public Nullable<System.DateTime> DocToDate { get; set; }
        public string PartyTo { get; set; }
        public string Attention { get; set; }
        public string CurrencyId { get; set; }
        public string Term { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public Nullable<decimal> Gp20 { get; set; }
        public Nullable<decimal> Gp40 { get; set; }
        public Nullable<decimal> Hc40 { get; set; }
        public Nullable<int> TransmitDay { get; set; }
        public string Description { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
    }
}
