//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_right
    {
        public int Id { get; set; }
        public Nullable<int> userid { get; set; }
        public string module_code { get; set; }
        public string page_code { get; set; }
        public string action_code { get; set; }
        public string access_level { get; set; }
        public string status_code { get; set; }
        public string remark { get; set; }
    }
}
