//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_So
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string SoNo { get; set; }
        public Nullable<System.DateTime> SoDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string PoNo { get; set; }
        public string PartyId { get; set; }
        public string PartyRefNo { get; set; }
        public string WarehouseId { get; set; }
        public string SalesmanId { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> DocAmt { get; set; }
        public Nullable<decimal> LocAmt { get; set; }
        public string StatusCode { get; set; }
        public string PartyOrderNo { get; set; }
        public string Customer1 { get; set; }
        public string Customer2 { get; set; }
        public string Customer3 { get; set; }
        public string Customer4 { get; set; }
        public string Customer5 { get; set; }
        public string Customer6 { get; set; }
        public string Customer7 { get; set; }
        public string Customer8 { get; set; }
    }
}
