//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wh_Schedule
    {
        public int Id { get; set; }
        public string DoNo { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PartyId { get; set; }
        public string PartyName { get; set; }
        public string PartyAdd { get; set; }
        public string PartyContact { get; set; }
        public string LotNo { get; set; }
        public string Product { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> DoDateTime { get; set; }
        public string SalesId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public string DoctorId { get; set; }
        public string Patient { get; set; }
        public string StatusCode { get; set; }
    }
}
