//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wh_TransDet
    {
        public int Id { get; set; }
        public string DoNo { get; set; }
        public string DoType { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> BalQty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public string GstType { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public Nullable<decimal> DocAmt { get; set; }
        public Nullable<decimal> GstAmt { get; set; }
        public Nullable<decimal> LocAmt { get; set; }
        public Nullable<decimal> LineLocAmt { get; set; }
        public Nullable<System.DateTime> PeroidDate { get; set; }
        public string DoInNo { get; set; }
        public string ContractNo { get; set; }
        public string DoInId { get; set; }
        public Nullable<int> PreQty { get; set; }
        public string IsSch { get; set; }
        public Nullable<int> LastSchQty { get; set; }
        public string JobStatus { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Size { get; set; }
        public string PackCode { get; set; }
        public Nullable<int> Qty1 { get; set; }
        public Nullable<int> Qty2 { get; set; }
        public string LocationCode { get; set; }
        public string Unit { get; set; }
        public string Des1 { get; set; }
        public string Packing { get; set; }
        public Nullable<int> Qty3 { get; set; }
        public Nullable<int> Qty4 { get; set; }
        public Nullable<int> Qty5 { get; set; }
        public string CreateBy { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Remark { get; set; }
        public string CustomsLot { get; set; }
        public string LotNo { get; set; }
        public string Uom1 { get; set; }
        public string Uom2 { get; set; }
        public string Uom3 { get; set; }
        public string Uom4 { get; set; }
        public Nullable<int> QtyPackWhole { get; set; }
        public Nullable<int> QtyWholeLoose { get; set; }
        public Nullable<int> QtyLooseBase { get; set; }
        public string Att1 { get; set; }
        public string Att2 { get; set; }
        public string Att3 { get; set; }
        public string Att4 { get; set; }
        public string Att5 { get; set; }
        public string Att6 { get; set; }
        public string Att7 { get; set; }
        public string Att8 { get; set; }
        public string Att9 { get; set; }
        public string Att10 { get; set; }
    }
}
