//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class X0
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string RowVersion { get; set; }
        public string RowType { get; set; }
        public string RowStatus { get; set; }
        public string RowCreateBy { get; set; }
        public Nullable<System.DateTime> RowCreateTime { get; set; }
        public string RowUpdateBy { get; set; }
        public Nullable<System.DateTime> RowUpdateTime { get; set; }
        public string EntityNo { get; set; }
        public string EntityType { get; set; }
        public Nullable<System.DateTime> EntityDate { get; set; }
        public string EntityName { get; set; }
        public string ProcessStatus { get; set; }
        public string ProcessBy { get; set; }
        public Nullable<System.DateTime> ProcessTime { get; set; }
        public string ProcessNote { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public Nullable<System.DateTime> ActualDate { get; set; }
        public string PartyCode { get; set; }
        public string PartyName { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public string Status4 { get; set; }
        public string Status5 { get; set; }
        public string Status6 { get; set; }
        public string Status7 { get; set; }
        public string Status8 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Note5 { get; set; }
        public string Note6 { get; set; }
        public string Note7 { get; set; }
        public string Note8 { get; set; }
        public string Note9 { get; set; }
        public string Note10 { get; set; }
        public string Note11 { get; set; }
        public string Note12 { get; set; }
        public string Note13 { get; set; }
        public string Note14 { get; set; }
        public string Note15 { get; set; }
        public string Note16 { get; set; }
        public string Note17 { get; set; }
        public string Note18 { get; set; }
        public string Note19 { get; set; }
        public string Note20 { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public Nullable<decimal> Value4 { get; set; }
        public Nullable<decimal> Value5 { get; set; }
        public Nullable<decimal> Value6 { get; set; }
        public Nullable<decimal> Value7 { get; set; }
        public Nullable<decimal> Value8 { get; set; }
        public Nullable<decimal> Value9 { get; set; }
        public Nullable<decimal> Value10 { get; set; }
        public Nullable<decimal> Value11 { get; set; }
        public Nullable<decimal> Value12 { get; set; }
        public Nullable<decimal> Value13 { get; set; }
        public Nullable<decimal> Value14 { get; set; }
        public Nullable<decimal> Value15 { get; set; }
        public Nullable<decimal> Value16 { get; set; }
        public Nullable<decimal> Value17 { get; set; }
        public Nullable<decimal> Value18 { get; set; }
        public Nullable<decimal> Value19 { get; set; }
        public Nullable<decimal> Value20 { get; set; }
        public Nullable<int> Qty1 { get; set; }
        public Nullable<int> Qty2 { get; set; }
        public Nullable<int> Qty3 { get; set; }
        public Nullable<int> Qty4 { get; set; }
        public Nullable<int> Qty5 { get; set; }
        public Nullable<int> Qty6 { get; set; }
        public Nullable<int> Qty7 { get; set; }
        public Nullable<int> Qty8 { get; set; }
        public Nullable<int> Qty9 { get; set; }
        public Nullable<int> Qty10 { get; set; }
        public Nullable<int> Qty11 { get; set; }
        public Nullable<int> Qty12 { get; set; }
        public Nullable<int> Qty13 { get; set; }
        public Nullable<int> Qty14 { get; set; }
        public Nullable<int> Qty15 { get; set; }
        public Nullable<int> Qty16 { get; set; }
        public Nullable<int> Qty17 { get; set; }
        public Nullable<int> Qty18 { get; set; }
        public Nullable<int> Qty19 { get; set; }
        public Nullable<int> Qty20 { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public string User11 { get; set; }
        public string User12 { get; set; }
        public string User13 { get; set; }
        public string User14 { get; set; }
        public string User15 { get; set; }
        public string User16 { get; set; }
        public string User17 { get; set; }
        public string User18 { get; set; }
        public string User19 { get; set; }
        public string User20 { get; set; }
    }
}
