//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class X7
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string RowVersion { get; set; }
        public string RowType { get; set; }
        public string RowStatus { get; set; }
        public string RowCreateBy { get; set; }
        public Nullable<System.DateTime> RowCreateTime { get; set; }
        public string RowUpdateBy { get; set; }
        public Nullable<System.DateTime> RowUpdateTime { get; set; }
        public string ListCode { get; set; }
        public string ListType { get; set; }
        public string ListName { get; set; }
        public string ListGroup1 { get; set; }
        public string ListGroup2 { get; set; }
        public Nullable<decimal> ListValue1 { get; set; }
        public Nullable<decimal> ListValue2 { get; set; }
        public Nullable<System.DateTime> ListDate1 { get; set; }
        public Nullable<System.DateTime> ListDate2 { get; set; }
    }
}
