//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAJournalEntry
    {
        public int SequenceId { get; set; }
        public string ArApInd { get; set; }
        public string DocNo { get; set; }
        public string DocType { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public Nullable<int> AcYear { get; set; }
        public Nullable<int> AcPeriod { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public Nullable<decimal> DbAmt { get; set; }
        public Nullable<decimal> CurrencyCrAmt { get; set; }
        public Nullable<decimal> CurrencyDbAmt { get; set; }
        public string Remark { get; set; }
        public string PostInd { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string ReleaseInd { get; set; }
        public string CancelInd { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string PartyTo { get; set; }
        public string PartyType { get; set; }
        public string OtherPartyName { get; set; }
        public string ChqNo { get; set; }
        public string SupplierBillNo { get; set; }
        public Nullable<System.DateTime> SupplierBillDate { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
    }
}
