//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XXChgCode
    {
        public int SequenceId { get; set; }
        public string ChgcodeId { get; set; }
        public string ChgcodeDes { get; set; }
        public string ChgUnit { get; set; }
        public string GstTypeId { get; set; }
        public Nullable<decimal> GstP { get; set; }
        public string ChgTypeId { get; set; }
        public string ArCode { get; set; }
        public string ApCode { get; set; }
        public string ImpExpInd { get; set; }
        public string ArShortcutCode { get; set; }
        public string ApShortcutCode { get; set; }
        public string Quotation_Ind { get; set; }
        public Nullable<decimal> SortIndex { get; set; }
    }
}
