//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class XXSetup2
    {
        public int SequenceId { get; set; }
        public string MastId { get; set; }
        public Nullable<int> Year { get; set; }
        public string YearCurrentNo { get; set; }
        public string Mth01CurrentNo { get; set; }
        public string Mth02CurrentNo { get; set; }
        public string Mth03CurrentNo { get; set; }
        public string Mth04CurrentNo { get; set; }
        public string Mth05CurrentNo { get; set; }
        public string Mth06CurrentNo { get; set; }
        public string Mth07CurrentNo { get; set; }
        public string Mth08CurrentNo { get; set; }
        public string Mth09CurrentNo { get; set; }
        public string Mth10CurrentNo { get; set; }
        public string Mth11CurrentNo { get; set; }
        public string Mth12CurrentNo { get; set; }
    }
}
