//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_data_stock
    {
        public int Id { get; set; }
        public string info_wh { get; set; }
        public string info_clientname { get; set; }
        public string info_clientcode { get; set; }
        public Nullable<decimal> info_qty { get; set; }
        public Nullable<decimal> info_cbm { get; set; }
        public Nullable<decimal> info_kgs { get; set; }
        public string info_item { get; set; }
        public string info_desc { get; set; }
        public string info_unit { get; set; }
        public string info_remark { get; set; }
        public string info_mark { get; set; }
        public Nullable<decimal> info_l { get; set; }
        public Nullable<decimal> info_w { get; set; }
        public Nullable<decimal> info_h { get; set; }
        public Nullable<System.DateTime> info_datein { get; set; }
        public string info_permit { get; set; }
    }
}
