//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class z_data3
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Add1 { get; set; }
        public string Add2 { get; set; }
        public string Add3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Postal { get; set; }
        public string TaxCode { get; set; }
        public string TermCode { get; set; }
        public string Contact1 { get; set; }
        public string Tel1 { get; set; }
        public string Mobile1 { get; set; }
        public string Memo { get; set; }
        public string CreateDate { get; set; }
    }
}
