//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirExport
    {
        public int SequenceId { get; set; }
        public string RefNo { get; set; }
        public string ContainerNo { get; set; }
        public string JobNo { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public string HblNo { get; set; }
        public string CustomerId { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string FrtTerm { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public string PlaceDeliveryId { get; set; }
        public string PlaceDeliveryname { get; set; }
        public string PlaceReceiveId { get; set; }
        public string PlaceReceiveName { get; set; }
        public string PlaceDeliveryTerm { get; set; }
        public string PlaceReceiveTerm { get; set; }
        public string PreCarriage { get; set; }
        public string ShipOnBoardInd { get; set; }
        public Nullable<System.DateTime> ShipOnBoardDate { get; set; }
        public string ShipLoadInd { get; set; }
        public string ExpressBl { get; set; }
        public string TsInd { get; set; }
        public string TsJobNo { get; set; }
        public string PermitRmk { get; set; }
        public string SShipperRemark { get; set; }
        public string SAgentRemark { get; set; }
        public string SConsigneeRemark { get; set; }
        public string SNotifyPartyRemark { get; set; }
        public Nullable<decimal> ImpCharge { get; set; }
        public string HaulierName { get; set; }
        public string HaulierCrNo { get; set; }
        public string HaulierAttention { get; set; }
        public string HaulierCollect { get; set; }
        public string HaulierTruck { get; set; }
        public Nullable<System.DateTime> HaulierCollectDate { get; set; }
        public string HaulierRemark { get; set; }
    }
}
