//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cont_AssetEvent
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string DocNo { get; set; }
        public string DocType { get; set; }
        public string JobNo { get; set; }
        public string EventCode { get; set; }
        public Nullable<System.DateTime> EventDateTime { get; set; }
        public string EventPort { get; set; }
        public string EventDepot { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public string VehicleNo { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string Insturction { get; set; }
        public string ContainerNo { get; set; }
        public string ContainerType { get; set; }
    }
}
