//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_Job_Recover
    {
        public int Id { get; set; }
        public string JobNo { get; set; }
        public Nullable<System.DateTime> JobDate { get; set; }
        public string PartyId { get; set; }
        public string Vessel { get; set; }
        public string Voyage { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public Nullable<System.DateTime> EtaDate { get; set; }
        public string EtaTime { get; set; }
        public Nullable<System.DateTime> EtdDate { get; set; }
        public string EtdTime { get; set; }
        public string CarrierId { get; set; }
        public string CarrierBlNo { get; set; }
        public string CarrierBkgNo { get; set; }
        public string PickupFrom { get; set; }
        public string DeliveryTo { get; set; }
        public string Remark { get; set; }
        public string SpecialInstruction { get; set; }
        public string StatusCode { get; set; }
        public string Terminalcode { get; set; }
        public string JobType { get; set; }
        public string ClientId { get; set; }
        public string ClientRefNo { get; set; }
        public string HaulierId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<System.DateTime> CodDate { get; set; }
        public string CodTime { get; set; }
        public string WarehouseAddress { get; set; }
        public string PermitNo { get; set; }
        public string YardRef { get; set; }
        public string PortnetRef { get; set; }
        public string OperatorCode { get; set; }
    }
}
