//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTM_JobEventLog
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string Controller { get; set; }
        public string JobNo { get; set; }
        public string ContainerNo { get; set; }
        public string Trip { get; set; }
        public string Driver { get; set; }
        public string Towhead { get; set; }
        public string Trail { get; set; }
        public string Remark { get; set; }
        public string Note1 { get; set; }
        public string Note2 { get; set; }
        public string Note3 { get; set; }
        public string Note4 { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Platform { get; set; }
        public string ParentJobNo { get; set; }
        public string ParentJobType { get; set; }
        public string JobType { get; set; }
        public string Note1Type { get; set; }
        public string JobStatus { get; set; }
        public Nullable<decimal> Value1 { get; set; }
        public Nullable<decimal> Value2 { get; set; }
        public Nullable<decimal> Value3 { get; set; }
        public Nullable<decimal> Value4 { get; set; }
        public Nullable<decimal> Value5 { get; set; }
        public Nullable<decimal> Value6 { get; set; }
        public Nullable<decimal> Value7 { get; set; }
        public Nullable<decimal> Value8 { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionLevel { get; set; }
        public string ActionType { get; set; }
    }
}
