//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_Leave
    {
        public int Id { get; set; }
        public Nullable<int> Person { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Time1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string Time2 { get; set; }
        public string Days { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ApplyDateTime { get; set; }
        public Nullable<int> ApproveBy { get; set; }
        public string ApproveStatus { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string ApproveRemark { get; set; }
        public string ApproveTime { get; set; }
        public string LeaveType { get; set; }
    }
}
