//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_stock
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string JobNo { get; set; }
        public string ContNo { get; set; }
        public Nullable<int> LineId { get; set; }
        public string Marks1 { get; set; }
        public string Marks2 { get; set; }
        public string Desc1 { get; set; }
        public string Desc2 { get; set; }
        public Nullable<int> Qty1 { get; set; }
        public Nullable<int> Qty2 { get; set; }
        public string Uom1 { get; set; }
        public string Uom2 { get; set; }
        public Nullable<decimal> Price1 { get; set; }
        public Nullable<decimal> Price2 { get; set; }
        public Nullable<decimal> Amount1 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> CBM { get; set; }
        public string Dimension { get; set; }
        public Nullable<decimal> W1 { get; set; }
        public Nullable<decimal> H1 { get; set; }
        public Nullable<decimal> L1 { get; set; }
        public Nullable<decimal> W2 { get; set; }
        public Nullable<decimal> H2 { get; set; }
        public Nullable<decimal> L2 { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public string PipeNo { get; set; }
        public string HintNo { get; set; }
    }
}
