//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_text
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string RowStatus { get; set; }
        public string RowCreateUser { get; set; }
        public Nullable<System.DateTime> RowCreateTime { get; set; }
        public string RowUpdateUser { get; set; }
        public Nullable<System.DateTime> RowUpdateTime { get; set; }
    }
}
