//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobCrews
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string HrRole { get; set; }
        public string Tel { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public string Postalcode { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> JobTime { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public Nullable<decimal> WorkHour { get; set; }
        public Nullable<decimal> OtHour { get; set; }
        public Nullable<decimal> PayTotal { get; set; }
        public string PayNote { get; set; }
        public Nullable<decimal> Amount1 { get; set; }
        public Nullable<decimal> Amount2 { get; set; }
        public Nullable<decimal> Amount3 { get; set; }
        public Nullable<decimal> Amount4 { get; set; }
        public Nullable<decimal> Amount5 { get; set; }
        public Nullable<decimal> Amount6 { get; set; }
        public Nullable<decimal> Amount7 { get; set; }
        public Nullable<decimal> Amount8 { get; set; }
        public string IsPay { get; set; }
    }
}
