//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string Code { get; set; }
        public Nullable<int> RequisitionNew { get; set; }
        public Nullable<int> RequisitionUsed { get; set; }
        public Nullable<int> AdditionalNew { get; set; }
        public Nullable<int> AdditionalUsed { get; set; }
        public Nullable<int> AdditionalNew1 { get; set; }
        public Nullable<int> AdditionalUsed1 { get; set; }
        public Nullable<int> AdditionalNew2 { get; set; }
        public Nullable<int> AdditionalUsed2 { get; set; }
        public Nullable<int> ReturnedNew { get; set; }
        public Nullable<int> ReturnedUsed { get; set; }
        public Nullable<int> TotalNew { get; set; }
        public Nullable<int> TotalUsed { get; set; }
        public string RefNo { get; set; }
        public Nullable<int> RequisitionNew1 { get; set; }
        public Nullable<int> RequisitionUsed1 { get; set; }
        public Nullable<int> RequisitionNew2 { get; set; }
        public Nullable<int> RequisitionUsed2 { get; set; }
        public string DocNo { get; set; }
        public string DocType { get; set; }
        public string DocOwner { get; set; }
        public string BillNo { get; set; }
        public string BillTerm { get; set; }
        public string PoNo { get; set; }
        public string DocStatus { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string PartyTo { get; set; }
        public string PartyAddress { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string GstType { get; set; }
        public Nullable<decimal> GstAmt { get; set; }
        public Nullable<decimal> DocAmt { get; set; }
        public string ActionType { get; set; }
        public string ActionUser { get; set; }
        public Nullable<System.DateTime> ActionTime { get; set; }
    }
}
