//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class pts_item
    {
        public int Id { get; set; }
        public Nullable<int> company_id { get; set; }
        public string company_reg { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> cate_id { get; set; }
        public string item_code { get; set; }
        public string item_name { get; set; }
        public Nullable<decimal> pts_value1 { get; set; }
        public Nullable<decimal> pts_value2 { get; set; }
        public Nullable<decimal> pts_value3 { get; set; }
        public Nullable<decimal> pts_value4 { get; set; }
        public Nullable<decimal> pts_value5 { get; set; }
        public string pts_name1 { get; set; }
        public string pts_name2 { get; set; }
        public string pts_name3 { get; set; }
        public string pts_name4 { get; set; }
        public string pts_name5 { get; set; }
    }
}
