//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_PersonInfo
    {
        public int Id { get; set; }
        public string PartyId { get; set; }
        public string ICNo { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Contact { get; set; }
        public string AccountNo { get; set; }
        public string Type { get; set; }
        public string Address { get; set; }
        public string RelationId { get; set; }
    }
}
