//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ref_location
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string WarehouseCode { get; set; }
        public string ZoneCode { get; set; }
        public string StoreCode { get; set; }
        public string PartyId { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> length { get; set; }
        public Nullable<decimal> width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> ToLeft { get; set; }
        public Nullable<decimal> ToTop { get; set; }
        public Nullable<decimal> SpaceM3 { get; set; }
        public string Loclevel { get; set; }
        public Nullable<decimal> MaxCount { get; set; }
        public string StorageType { get; set; }
        public string StorageTemp { get; set; }
    }
}
