//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaApQuote1
    {
        public int SequenceId { get; set; }
        public string PartyTo { get; set; }
        public string PartyType { get; set; }
        public string Port { get; set; }
        public string ViaPort { get; set; }
        public string ImpExpInd { get; set; }
        public string FclLclInd { get; set; }
        public string Frequency { get; set; }
        public Nullable<decimal> LclChg { get; set; }
        public string Subject { get; set; }
        public string QuoteNo { get; set; }
        public string Status { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public string Rmk { get; set; }
        public string Attention { get; set; }
        public string TransmitDay { get; set; }
        public Nullable<decimal> Gp20 { get; set; }
        public Nullable<decimal> Gp40 { get; set; }
        public Nullable<decimal> Hc40 { get; set; }
        public string CurrencyId { get; set; }
        public string SalesmanId { get; set; }
        public string Note { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public string Title { get; set; }
        public string ContType { get; set; }
        public Nullable<decimal> ContPrice { get; set; }
        public Nullable<decimal> ExRate { get; set; }
    }
}
