//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeaQuoteDet1
    {
        public int SequenceId { get; set; }
        public string QuoteId { get; set; }
        public Nullable<int> QuoteLineNo { get; set; }
        public string PartyTo { get; set; }
        public string PartyType { get; set; }
        public string ImpExpInd { get; set; }
        public string FclLclInd { get; set; }
        public string ChgCode { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> MinAmt { get; set; }
        public string Rmk { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Amt { get; set; }
        public string GstType { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public string GroupTitle { get; set; }
        public string ChgDes { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public string Pol { get; set; }
        public string Pod { get; set; }
        public Nullable<decimal> MinQty { get; set; }
        public string CarrierId { get; set; }
        public string AgentId { get; set; }
        public string CngId { get; set; }
        public string ShipType { get; set; }
        public string Status1 { get; set; }
        public string Status2 { get; set; }
        public string Status3 { get; set; }
        public string Status4 { get; set; }
        public string Status5 { get; set; }
        public string Status6 { get; set; }
        public string Status7 { get; set; }
        public string Status8 { get; set; }
        public string Status9 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public Nullable<System.DateTime> Date3 { get; set; }
        public Nullable<System.DateTime> Date4 { get; set; }
        public Nullable<System.DateTime> Date5 { get; set; }
        public Nullable<System.DateTime> Date6 { get; set; }
        public Nullable<System.DateTime> Date7 { get; set; }
        public Nullable<System.DateTime> Date8 { get; set; }
        public Nullable<decimal> Rate1 { get; set; }
        public Nullable<decimal> Rate2 { get; set; }
        public Nullable<decimal> Rate3 { get; set; }
        public Nullable<decimal> Rate4 { get; set; }
        public Nullable<decimal> Rate5 { get; set; }
        public Nullable<decimal> Rate6 { get; set; }
        public Nullable<decimal> Rate7 { get; set; }
        public Nullable<decimal> Rate8 { get; set; }
        public Nullable<decimal> Rate9 { get; set; }
        public Nullable<decimal> Rate10 { get; set; }
        public Nullable<decimal> Rate11 { get; set; }
        public Nullable<decimal> Rate12 { get; set; }
        public Nullable<decimal> Rate13 { get; set; }
        public Nullable<decimal> Rate14 { get; set; }
        public Nullable<decimal> Rate15 { get; set; }
        public Nullable<decimal> Rate16 { get; set; }
        public Nullable<decimal> Rate17 { get; set; }
        public Nullable<decimal> Rate18 { get; set; }
        public Nullable<decimal> Rate19 { get; set; }
        public string user_create { get; set; }
        public Nullable<System.DateTime> time_create { get; set; }
        public string user_update { get; set; }
        public Nullable<System.DateTime> time_update { get; set; }
    }
}
