//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class sys_alert_rule
    {
        public int Id { get; set; }
        public string AlertSql { get; set; }
        public string AlertTo { get; set; }
        public string AlertCc { get; set; }
        public string AlertBcc { get; set; }
        public string AlertMobile { get; set; }
        public string AlertBody { get; set; }
        public string AlertSubject { get; set; }
        public string AlertSms { get; set; }
        public string AlertColumns { get; set; }
        public string MasterId { get; set; }
        public string Code { get; set; }
        public string SubjectPosition { get; set; }
        public string BodyPosition { get; set; }
    }
}
