//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tpt_Job1
    {
        public int Id { get; set; }
        public string TptNo { get; set; }
        public string Remark { get; set; }
        public string JobNo { get; set; }
        public string JobType { get; set; }
        public Nullable<System.DateTime> TptDate { get; set; }
        public string CustomerId { get; set; }
        public string ShipperName { get; set; }
        public string Consignee { get; set; }
        public string PickupFrom { get; set; }
        public string DeliveryTo { get; set; }
        public Nullable<System.DateTime> PickupDate { get; set; }
        public string PickupTime { get; set; }
        public Nullable<System.DateTime> DeliveryToDate { get; set; }
        public string DeliveryToTime { get; set; }
        public string HaulierId { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public Nullable<int> Qty { get; set; }
        public string PackageType { get; set; }
        public string Driver { get; set; }
        public string TptType { get; set; }
        public string CloseInd { get; set; }
        public Nullable<System.DateTime> CloseDate { get; set; }
        public string CloseUser { get; set; }
    }
}
