//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int SequenceId { get; set; }
        public string Name { get; set; }
        public string Pwd { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Role { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CustId { get; set; }
        public string Port { get; set; }
        public string EventDepot { get; set; }
        public string CompanyCode { get; set; }
        public string CompanyRole { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string OptionType { get; set; }
    }
}
