//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class wh_SoReleaseDet
    {
        public int Id { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string ReleaseNo { get; set; }
        public string ReleaseType { get; set; }
        public string SoNo { get; set; }
        public Nullable<int> LineSNo { get; set; }
        public string Product { get; set; }
        public string Uom { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string GstType { get; set; }
        public Nullable<decimal> Gst { get; set; }
        public Nullable<decimal> DocAmt { get; set; }
        public Nullable<decimal> GstAmt { get; set; }
        public Nullable<decimal> LocAmt { get; set; }
        public Nullable<decimal> LineLocAmt { get; set; }
        public string LocCode { get; set; }
    }
}
