//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XAGlEntryDet
    {
        public int SequenceId { get; set; }
        public string ArApInd { get; set; }
        public Nullable<int> GlLineNo { get; set; }
        public Nullable<int> AcYear { get; set; }
        public Nullable<int> AcPeriod { get; set; }
        public string AcCode { get; set; }
        public string AcSource { get; set; }
        public string DocNo { get; set; }
        public string DocType { get; set; }
        public string CurrencyId { get; set; }
        public Nullable<decimal> ExRate { get; set; }
        public Nullable<decimal> CrAmt { get; set; }
        public Nullable<decimal> DbAmt { get; set; }
        public Nullable<decimal> CurrencyCrAmt { get; set; }
        public Nullable<decimal> CurrencyDbAmt { get; set; }
        public string Remark { get; set; }
        public Nullable<int> GlNo { get; set; }
        public string ChgCode { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string MastRefNo { get; set; }
        public string JobRefNo { get; set; }
        public string MastType { get; set; }
        public string Dim1 { get; set; }
        public string Dim2 { get; set; }
        public string Dim3 { get; set; }
        public string Dim4 { get; set; }
    }
}
