//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XXParty
    {
        public int SequenceId { get; set; }
        public string PartyId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsCustomer { get; set; }
        public Nullable<bool> IsVendor { get; set; }
        public Nullable<bool> IsAgent { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Fax1 { get; set; }
        public string Fax2 { get; set; }
        public string Email1 { get; set; }
        public string Email2 { get; set; }
        public string Contact1 { get; set; }
        public string Contact2 { get; set; }
        public string CountryId { get; set; }
        public string SalesmanId { get; set; }
        public string PortId { get; set; }
        public string Remark { get; set; }
        public string CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDateTime { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public string TermId { get; set; }
        public string GroupId { get; set; }
        public string CrNo { get; set; }
        public string CarrierCode { get; set; }
        public Nullable<decimal> WarningAmt { get; set; }
        public Nullable<int> WarningQty { get; set; }
        public Nullable<decimal> BlockAmt { get; set; }
        public Nullable<int> BlockQty { get; set; }
        public string ZipCode { get; set; }
        public string City { get; set; }
        public string Address1 { get; set; }
        public string ClientType { get; set; }
        public string ParentCode { get; set; }
        public string BillingAlert { get; set; }
        public string LoginInd { get; set; }
        public string LoginPw { get; set; }
        public string LoginPW1 { get; set; }
        public string LoginCode { get; set; }
    }
}
